// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var SubstreamOp = exports.SubstreamOp = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineSubstreamOp()

function defineSubstreamOp () {
  var enc = [
    encodings.varint,
    encodings.bytes
  ]

  SubstreamOp.encodingLength = encodingLength
  SubstreamOp.encode = encode
  SubstreamOp.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.op)) throw new Error("op is required")
    var len = enc[0].encodingLength(obj.op)
    length += 1 + len
    if (!defined(obj.id)) throw new Error("id is required")
    var len = enc[1].encodingLength(obj.id)
    length += 1 + len
    if (defined(obj.data)) {
      var len = enc[1].encodingLength(obj.data)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.op)) throw new Error("op is required")
    buf[offset++] = 8
    enc[0].encode(obj.op, buf, offset)
    offset += enc[0].encode.bytes
    if (!defined(obj.id)) throw new Error("id is required")
    buf[offset++] = 18
    enc[1].encode(obj.id, buf, offset)
    offset += enc[1].encode.bytes
    if (defined(obj.data)) {
      buf[offset++] = 26
      enc[1].encode(obj.data, buf, offset)
      offset += enc[1].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      op: 0,
      id: null,
      data: null
    }
    var found0 = false
    var found1 = false
    while (true) {
      if (end <= offset) {
        if (!found0 || !found1) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.op = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found0 = true
        break
        case 2:
        obj.id = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        found1 = true
        break
        case 3:
        obj.data = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
